services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:10.14-alpine
    command: -configFiles=/flyway/conf/docker-flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/migrations:/flyway/sql
      - ${PWD}/config:/flyway/conf
    depends_on:
      - db
volumes:
  db:
    driver: local